# Generated by Django 4.1.5 on 2023-01-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_landlordpage_landlord_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_page_text', models.TextField(verbose_name='Investor Page')),
            ],
        ),
    ]
